server:
  pulsar: 
    plugin: https://archive.apache.org/dist/pulsar/pulsar-2.5.0/apache-pulsar-2.5.0-bin.tar.gz   
    version: 2.5.0
    folder: /presto/plugin
  presto:
    bin: https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.233.1/presto-server-0.233.1.tar.gz
    version: 0.233.1
    home: /presto
  workers: 2
  node:
    environment: production
    dataDir: /presto/etc/data
  log:
    presto:
      level: INFO
  config:
    path: /etc/presto
    http:
      port: 8081
    query:
      maxMemory: "4GB"
      maxMemoryPerNode: "1GB"
  jvm:
    maxHeapSize: "8G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"

image:
  repository: eabanonu/presto-pulsar
  tag: v0.0.12
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
